owner: cybertekne
repo: upptime

sites:
  - name: XDR
    url: https://dexdr01.cybertekne.com
  - name: CTI01
    url: https://decti01.cybertekne.com
  - name: CTI02
    url: https://decti02.cybertekne.com

status-website:
  cname: status.cybertekne.com
  logoUrl: https://brand.cybertekne.com/cybertekne.png
  name: CyberTekne Corp
  introTitle: "Real-Time Status"
  introMessage: Here you can find real-time information on the availability of our services. We monitor our systems continuously and update this page if we detect any issues.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
i18n:
  footer: This page is [open source]($REPO), powered by [Upptime](https://upptime.js.org)
